### ISSUE TITLE
error uploading to codeclimate after test is run

### ISSUE THREAD

**Issue by Maxcutex** [codeclimate/test-reporter#357]
i get the following error from circle ci when the test is done. 

`[Coveralls] Submitting to https://coveralls.io/api/v1
Coveralls encountered an exception:
RestClient::UnprocessableEntity
422 Unprocessable Entity
/usr/local/bundle/ruby/2.4.0/gems/rest-client-2.0.2/lib/restclient/abstract_response.rb:223:in `exception_with_response'
/usr/local/bundle/ruby/2.4.0/gems/rest-client-2.0.2/lib/restclient/abstract_response.rb:103:in `return!'
/usr/local/bundle/ruby/2.4.0/gems/rest-client-2.0.2/lib/restclient/request.rb:809:in `process_result'
/usr/local/bundle/ruby/2.4.0/gems/rest-client-2.0.2/lib/restclient/request.rb:725:in `block in transmit'
/usr/local/lib/ruby/2.4.0/net/http.rb:877:in `start'
/usr/local/bundle/ruby/2.4.0/gems/rest-client-2.0.2/lib/restclient/request.rb:715:in `transmit'
/usr/local/bundle/ruby/2.4.0/gems/rest-client-2.0.2/lib/restclient/request.rb:145:in `execute'
/usr/local/bundle/ruby/2.4.0/gems/rest-client-2.0.2/lib/restclient/request.rb:52:in `execute'
/usr/local/bundle/ruby/2.4.0/gems/rest-client-2.0.2/lib/restclient.rb:71:in `post'
/usr/local/bundle/ruby/2.4.0/gems/coveralls-0.7.1/lib/coveralls/api.rb:24:in `post_json'
/usr/local/bundle/ruby/2.4.0/gems/coveralls-0.7.1/lib/coveralls/simplecov.rb:72:in `format'
/usr/local/bundle/ruby/2.4.0/gems/simplecov-0.16.1/lib/simplecov/result.rb:48:in `format!'
/usr/local/bundle/ruby/2.4.0/gems/simplecov-0.16.1/lib/simplecov/configuration.rb:182:in `block in at_exit'
/usr/local/bundle/ruby/2.4.0/gems/simplecov-0.16.1/lib/simplecov.rb:200:in `run_exit_tasks!'
/usr/local/bundle/ruby/2.4.0/gems/simplecov-0.16.1/lib/simplecov/defaults.rb:27:in `block in <top (required)>'
{"message":"Couldn't find a repository matching this job.","error":true}`

What could be wrong?

**Comment by wfleming** [comment]
This looks like a stack trace for the [coveralls.io Ruby gem](http://docs.coveralls.io/ruby-on-rails), but this repository is for the [codeclimate.com test reporter](https://docs.codeclimate.com/docs/configuring-test-coverage). Different tools for different websites. Did you file this in the right place?

**Comment by Maxcutex** [comment]
i am using this sample code. found here 

https://docs.codeclimate.com/docs/circle-ci-test-coverage-example

**Comment by wfleming** [comment]
> however i wish to ask how to implement the lcov test function for the frontend in circle ci.

Can you please provide more details of how you were collecting the lcov report, where the report was located, how you were using `cc-test-reporter` to format that report before the `sum-coverage` call, in what way it wasn't working, and what error messages you were seeing?

**Comment by Maxcutex** [comment]
hi , 

i havent used it on circle ci before. i just used the example in the link above. is lcov installed in circle ci by default or is there a setting i need to enable ?

**Comment by Maxcutex** [comment]
Actually its is exactly the same. Which is why i asked what setup i need to get lcov running. For the test to work i removed the frontend tests part of the script and left the backend tests since it conforms with the way i want to run my test

find below the config that caused error 


version: 2.0
defaults: &defaults
  working_directory: ~/myapp
  docker:
    - image: circleci/ruby:2.4.1-node-browsers
      environment:
        RAILS_ENV: test
        PGHOST: 127.0.0.1
        DATABASE_URL: "postgres://ubuntu@localhost:5432/circle_test"
    - image: circleci/postgres:9.6
      environment:
        POSTGRES_USER: ubuntu
        POSTGRES_DB: circle_test
        POSTGRES_PASSWORD: ""
jobs:
  build:
    <<: *defaults
    steps:
      - run:
          name:  Download cc-test-reporter
          command: |
            mkdir -p tmp/
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
            chmod +x ./tmp/cc-test-reporter
      - persist_to_workspace:
          root: tmp
          paths:
            - cc-test-reporter
  backend-tests:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/myapp/tmp
      - run: 
          name: Setup dependencies
          command: |
            bundle install --without production --path=${BUNDLE_PATH:-vendor/bundle}
            bundle exec rake db:create db:migrate
      - run: 
          name: Run backend tests
          command: |
            bundle exec rake
            ./tmp/cc-test-reporter format-coverage -t simplecov -o tmp/codeclimate.backend.json coverage/backend/.resultset.json
      - persist_to_workspace:
          root: tmp
          paths: 
            - codeclimate.backend.json
  frontend-tests:
    <<: *defaults
    steps:
      - checkout 
      - attach_workspace:
          at: ~/myapp/tmp
      - run: npm install
      - run: 
          name: Run frontend testss
          command: |
            npm test
            ./tmp/cc-test-reporter format-coverage -t lcov -o tmp/codeclimate.frontend.json coverage/frontend/lcov.info
      - persist_to_workspace:
          root: tmp
          paths: 
            - codeclimate.frontend.json
  upload-coverage:
    <<: *defaults
    environment: 
      - CC_TEST_REPORTER_ID: MY_OWN_ID
    steps:
      - attach_workspace:
          at: ~/myapp/tmp
      - run:
          name: Upload coverage results to Code Climate
          command: |
            ./tmp/cc-test-reporter sum-coverage tmp/codeclimate.*.json -p 2 -o tmp/codeclimate.total.json
            ./tmp/cc-test-reporter upload-coverage -i tmp/codeclimate.total.json
workflows:
  version: 2

  commit:
    jobs:
      - build
      - backend-tests:
          requires:
            - build
      - frontend-tests: 
          requires: 
             - build
      - upload-coverage:
          requires:
             - backend-tests
             - frontend-tests

**Comment by wfleming** [comment]
Thank you, that config is helpful since it is not exactly the same as our examples and helps us understand how you're assembling the different test reports. What was the error you were seeing regarding the lcov report with this config?

**Comment by Maxcutex** [comment]
apologies i though i had uploaded the error along side. Find attached. 
![lcov_error](https://user-images.githubusercontent.com/27193978/45404819-60127600-b658-11e8-8f86-3a3995a8ec6d.JPG)

**Comment by wfleming** [comment]
The error is indicating that `coverage/frontend/lcov.info` does not exist when `cc-test-reporter` runs, have you confirmed it is being created at that path?

That "Error: no test specified" message, which I think is being echoed by your `npm test` command is interesting. Do you know what's causing that? That makes me think something that your frontend tests are not actually running on CI right now for some reason.

Alternatively, running the job with ssh enabled might make it easier for you to poke around the container and see what's on the filesystem, or adding some shell commands like `ls -alR coverage` before running the test reporter could help identify if the file does not exist at all or is perhaps being written to a different path for some reason.

**Comment by wfleming** [comment]
Closing due to inactivity
