### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by pbrisbin** [codeclimate/test-reporter#57]
Was just checking into the upload-coverage acceptance and am now hitting this:

```
% cc-test-reporter --version
Code Climate Test Reporter 0.1.0-rc (87b79108dbf28c770a56f0a0fa5f2d85ae6fba37 @ 2017-03-20T17:51:18+0000)
% cc-test-reporter format-coverage
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x6cdf9e]

goroutine 1 [running]:
github.com/codeclimate/test-reporter/cmd.CoverageFormatter.Save(0x78545e, 0x19, 0x0, 0x0, 0x0)
	/src/github.com/codeclimate/test-reporter/cmd/format-coverage.go:35 +0x6e
github.com/codeclimate/test-reporter/cmd.glob..func2(0x9222e0, 0x941fd8, 0x0, 0x0, 0x0, 0x0)
	/src/github.com/codeclimate/test-reporter/cmd/format-coverage.go:25 +0x44
github.com/codeclimate/test-reporter/vendor/github.com/spf13/cobra.(*Command).execute(0x9222e0, 0x941fd8, 0x0, 0x0, 0x9222e0, 0x941fd8)
	/src/github.com/codeclimate/test-reporter/vendor/github.com/spf13/cobra/command.go:644 +0x3ef
github.com/codeclimate/test-reporter/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x922500, 0x0, 0x24, 0x78b88c)
	/src/github.com/codeclimate/test-reporter/vendor/github.com/spf13/cobra/command.go:734 +0x339
github.com/codeclimate/test-reporter/vendor/github.com/spf13/cobra.(*Command).Execute(0x922500, 0xc420049f68, 0x6cff07)
	/src/github.com/codeclimate/test-reporter/vendor/github.com/spf13/cobra/command.go:693 +0x2b
github.com/codeclimate/test-reporter/cmd.Execute()
	/src/github.com/codeclimate/test-reporter/cmd/root.go:32 +0x2d
main.main()
	/src/github.com/codeclimate/test-reporter/main.go:20 +0x20
```

Yay memory unsafe languages!

**Comment by pbrisbin** [comment]
LGTM. Lucky, IMO, that I just happened to hit that edge case because of a bad `cd`!

**Comment by markbates** [comment]
It was a good catch. We should be checking to make sure there is something to format. Good catch!
